spring.application.name=DockDash

server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
jwt.secret=9a4f2c8d3e1f5b7a6c9d0e2f1a3b5c7d9e0f2a4b6c8d0e1f3a5b7c9d1e3f5a7
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html